# Auto generated from an XMI file
# Do not edit this file
# Edit admin_custom.py instead
from models import *
from admin_generic import *
from admin_custom import *
from django.contrib import admin



admin.site.register(SourceComponent_WorkComponent, SourceComponent_WorkComponentAdmin)
admin.site.register(WorkComponent, WorkComponentAdmin)
admin.site.register(Work, WorkAdmin)
admin.site.register(Opus, OpusAdmin)
admin.site.register(BarRegion, BarRegionAdmin)
admin.site.register(Bar, BarAdmin)
admin.site.register(Source, SourceAdmin)
admin.site.register(Genre, GenreAdmin)
admin.site.register(keyPitch, keyPitchAdmin)
admin.site.register(Instrument, InstrumentAdmin)
admin.site.register(keyMode, keyModeAdmin)
admin.site.register(SourceComponent, SourceComponentAdmin)
admin.site.register(Publisher, PublisherAdmin)
admin.site.register(WorkComponentType, WorkComponentTypeAdmin)
admin.site.register(instrumentComponent, instrumentComponentAdmin)
admin.site.register(WorkCollection, WorkCollectionAdmin)
admin.site.register(SourceInformation, SourceInformationAdmin)
admin.site.register(PageImage, PageImageAdmin)
admin.site.register(PageType, PageTypeAdmin)
admin.site.register(CollectionType, CollectionTypeAdmin)
admin.site.register(SourceComponentType, SourceComponentTypeAdmin)
admin.site.register(Page, PageAdmin)
admin.site.register(PageLegacy, PageLegacyAdmin)
admin.site.register(Archive, ArchiveAdmin)
admin.site.register(City, CityAdmin)
admin.site.register(Country, CountryAdmin)
admin.site.register(SourceType, SourceTypeAdmin)
admin.site.register(Year, YearAdmin)
admin.site.register(Dedicatee, DedicateeAdmin)
admin.site.register(PrintingMethod, PrintingMethodAdmin)
admin.site.register(WorkInformation, WorkInformationAdmin)
admin.site.register(Annotation, AnnotationAdmin)
admin.site.register(AnnotationType, AnnotationTypeAdmin)
admin.site.register(AcCode, AcCodeAdmin)
admin.site.register(NewSource)
admin.site.register(NewPageImage)
admin.site.register(EditStatus)
