# Generated by Django 3.2.9 on 2021-12-07 12:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('catalogue', '0007_drop_footnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impression',
            name='publisher',
        ),
        migrations.AddField(
            model_name='impression',
            name='impression_publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impressions', to='catalogue.publisher'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='content',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='impression',
            name='ocve_ac_code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='AC Code in CFEO/OCVE'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='library',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libraries', to='catalogue.city'),
        ),
        migrations.AlterField(
            model_name='library',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publishers', to='catalogue.city'),
        ),
        migrations.AlterField(
            model_name='stp',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='work',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document'),
        ),
    ]
