# Generated by Django 3.2.9 on 2021-12-07 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accode', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('accode_hash', models.CharField(editable=False, max_length=256)),
            ],
            options={
                'verbose_name': 'AcCode',
                'verbose_name_plural': 'AcCodes',
                'ordering': ['accode'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notetext', models.TextField(blank=True, default='')),
                ('noteregions', models.TextField(blank=True, default='')),
                ('geometry', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
            },
        ),
        migrations.CreateModel(
            name='Annotation_BarRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.annotation')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotationType', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('siglum', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barnumber', models.IntegerField(blank=True, null=True)),
                ('barlabel', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Bar',
                'verbose_name_plural': 'Bars',
            },
        ),
        migrations.CreateModel(
            name='Bar_BarRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.bar')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'CollectionType',
                'verbose_name_plural': 'CollectionTypes',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('countryabbrev', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Dedicatee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedicatee', models.TextField(blank=True, default='')),
                ('alternateOf', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alternate', to='ocve.dedicatee')),
            ],
            options={
                'verbose_name': 'Dedicatee',
                'verbose_name_plural': 'Dedicatees',
                'ordering': ['dedicatee'],
            },
        ),
        migrations.CreateModel(
            name='EditStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='NONE', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, default='', max_length=255)),
                ('pluralname', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Genre_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.genre')),
            ],
            options={
                'ordering': ['work'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(blank=True, default='', max_length=255)),
                ('instrumentabbrev', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
            },
        ),
        migrations.CreateModel(
            name='keyMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keymode', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'keyMode',
                'verbose_name_plural': 'keyModes',
            },
        ),
        migrations.CreateModel(
            name='keyPitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keypitch', models.CharField(blank=True, default='', max_length=255)),
                ('orderno', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'keyPitch',
                'verbose_name_plural': 'keyPitches',
                'ordering': ['orderno'],
            },
        ),
        migrations.CreateModel(
            name='NewSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, default='')),
                ('library', models.TextField(blank=True, default='')),
                ('copyright', models.TextField(blank=True, default='')),
                ('sourcecreated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Opus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opusno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Opus',
                'verbose_name_plural': 'Opuses',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, default='')),
                ('orderno', models.IntegerField(blank=True, null=True)),
                ('preferredversion', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surrogate', models.IntegerField(blank=True, null=True)),
                ('textlabel', models.TextField(blank=True, default='')),
                ('versionnumber', models.IntegerField(blank=True, null=True)),
                ('permission', models.BooleanField(default=False)),
                ('permissionnote', models.CharField(blank=True, default='', max_length=255)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('startbar', models.CharField(blank=True, default='', max_length=255)),
                ('endbar', models.CharField(blank=True, default='', max_length=255)),
                ('corrected', models.IntegerField(blank=True, null=True)),
                ('copyright', models.BooleanField(default=True)),
                ('page', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.page')),
            ],
            options={
                'verbose_name': 'PageImage',
                'verbose_name_plural': 'PageImages',
            },
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'PageType',
                'verbose_name_plural': 'PageTypes',
            },
        ),
        migrations.CreateModel(
            name='PrintingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'PrintingMethod',
                'verbose_name_plural': 'PrintingMethods',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('publisherAbbrev', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, default='')),
                ('cfeolabel', models.TextField(blank=True, default='')),
                ('ocve', models.BooleanField(default=False)),
                ('cfeo', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('orderno', models.IntegerField(default=999)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['orderno'],
            },
        ),
        migrations.CreateModel(
            name='SourceComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField(blank=True, null=True)),
                ('label', models.TextField(blank=True, default='')),
                ('instrumentnumber', models.IntegerField(blank=True, null=True)),
                ('instrumentkey', models.CharField(blank=True, default='', max_length=128)),
                ('overridelabel', models.TextField(blank=True, default='')),
                ('sourcecomponenttitle', models.CharField(blank=True, default='', help_text='e.g song titles like "Wojack"', max_length=255)),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.source')),
            ],
            options={
                'verbose_name': 'SourceComponent',
                'verbose_name_plural': 'SourceComponents',
                'ordering': ['orderno'],
            },
        ),
        migrations.CreateModel(
            name='SourceComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'SourceComponentType',
                'verbose_name_plural': 'SourceComponentTypes',
            },
        ),
        migrations.CreateModel(
            name='SourceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platenumber', models.CharField(blank=True, default='', max_length=255)),
                ('locationsimilarcopies', models.TextField(blank=True, default='')),
                ('reprints', models.TextField(blank=True, default='')),
                ('seriestitle', models.CharField(blank=True, default='', max_length=255)),
                ('copyright', models.CharField(blank=True, default='', max_length=255)),
                ('contentssummary', models.CharField(blank=True, default='', max_length=255)),
                ('contents', models.TextField(blank=True, default='')),
                ('shelfmark', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('datepublication', models.CharField(blank=True, default='', max_length=255)),
                ('leaves', models.CharField(blank=True, default='', max_length=255)),
                ('sourcecode', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.TextField(blank=True, default='')),
                ('publicationtitle', models.TextField(blank=True, default='')),
                ('imagesource', models.CharField(blank=True, default='', max_length=255)),
                ('additionalInformation', models.TextField(blank=True, default='')),
                ('keyFeatures', models.TextField(blank=True, default='')),
                ('volume', models.CharField(blank=True, default='', max_length=255)),
                ('displayedcopy', models.CharField(blank=True, default='', max_length=255)),
                ('accode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.accode')),
                ('archive', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.archive')),
                ('dedicatee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.dedicatee')),
                ('placepublication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocve.city')),
            ],
            options={
                'verbose_name': 'SourceInformation',
                'verbose_name_plural': 'SourceInformations',
            },
        ),
        migrations.CreateModel(
            name='SourceInformation_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.sourceinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'SourceType',
                'verbose_name_plural': 'SourceTypes',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('label', models.TextField(blank=True, default='')),
                ('orderno', models.IntegerField(blank=True, null=True)),
                ('genre', models.ManyToManyField(default=1, through='ocve.Genre_Work', to='ocve.Genre')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'ordering': ['orderno'],
            },
        ),
        migrations.CreateModel(
            name='WorkComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'WorkComponentType',
                'verbose_name_plural': 'WorkComponentTypes',
            },
        ),
        migrations.CreateModel(
            name='WorkInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalinfo', models.TextField(blank=True, default='', help_text='Publication History for this work')),
                ('relevantmanuscripts', models.TextField(blank=True, default='')),
                ('analysis', models.TextField(blank=True, default='')),
                ('OCVE', models.TextField(blank=True, default='', help_text='Only field displayed in OCVE work summary')),
            ],
            options={
                'verbose_name': 'WorkInformation',
                'verbose_name_plural': 'WorkInformations',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('sourceinformation', models.ManyToManyField(default=1, through='ocve.SourceInformation_Year', to='ocve.SourceInformation')),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='WorkComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField(blank=True, null=True)),
                ('label', models.TextField(blank=True, default='')),
                ('music', models.IntegerField(blank=True, null=True)),
                ('keymode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.keymode')),
                ('keypitch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.keypitch')),
                ('opus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.opus')),
                ('work', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.work')),
            ],
            options={
                'verbose_name': 'WorkComponent',
                'verbose_name_plural': 'WorkComponents',
            },
        ),
        migrations.CreateModel(
            name='WorkCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, default='')),
                ('overridelabel', models.TextField(blank=True, default='')),
                ('collectiontype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.collectiontype')),
            ],
            options={
                'verbose_name': 'WorkCollection',
                'verbose_name_plural': 'WorkCollections',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='workcollection',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ocve.workcollection'),
        ),
        migrations.AddField(
            model_name='work',
            name='workinformation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.workinformation'),
        ),
        migrations.CreateModel(
            name='SourceLegacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfeoKey', models.IntegerField(blank=True, default=0, null=True)),
                ('witnessKey', models.IntegerField(blank=True, default=0, null=True)),
                ('sourceDesc', models.TextField(blank=True, default='')),
                ('mellon', models.BooleanField(default=False)),
                ('needsBarLines', models.BooleanField(default=False)),
                ('editstatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.editstatus')),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.source')),
            ],
        ),
        migrations.AddField(
            model_name='sourceinformation_year',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.year'),
        ),
        migrations.CreateModel(
            name='SourceInformation_PrintingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printingmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.printingmethod')),
                ('sourceinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.sourceinformation')),
            ],
        ),
        migrations.AddField(
            model_name='sourceinformation',
            name='printingmethod',
            field=models.ManyToManyField(default=1, through='ocve.SourceInformation_PrintingMethod', to='ocve.PrintingMethod'),
        ),
        migrations.AddField(
            model_name='sourceinformation',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.publisher'),
        ),
        migrations.AddField(
            model_name='sourceinformation',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.source'),
        ),
        migrations.CreateModel(
            name='SourceComponent_WorkComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcecomponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.sourcecomponent')),
                ('workcomponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.workcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='SourceComponent_Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.instrument')),
                ('sourcecomponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.sourcecomponent')),
            ],
        ),
        migrations.AddField(
            model_name='sourcecomponent',
            name='sourcecomponenttype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.sourcecomponenttype'),
        ),
        migrations.AddField(
            model_name='source',
            name='sourcetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.sourcetype'),
        ),
        migrations.CreateModel(
            name='PageLegacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocveKey', models.IntegerField(blank=True, null=True)),
                ('cfeoKey', models.IntegerField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, default='')),
                ('storageStructure', models.TextField(blank=True, default='')),
                ('cropCorrected', models.IntegerField(blank=True, default=0, null=True)),
                ('jp2', models.CharField(blank=True, default='UNVERIFIED', max_length=255)),
                ('editstatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.editstatus')),
                ('pageimage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.pageimage')),
            ],
            options={
                'verbose_name': 'Page Legacy',
                'verbose_name_plural': 'Page Legacy',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='pagetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.pagetype'),
        ),
        migrations.AddField(
            model_name='page',
            name='sourcecomponent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.sourcecomponent'),
        ),
        migrations.CreateModel(
            name='NewSourceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationsimilarcopies', models.TextField(blank=True, default='')),
                ('reprints', models.TextField(blank=True, default='')),
                ('seriestitle', models.CharField(blank=True, default='', max_length=255)),
                ('copyright', models.CharField(blank=True, default='', max_length=255)),
                ('contentssummary', models.CharField(blank=True, default='', max_length=255)),
                ('contents', models.TextField(blank=True, default='', help_text='Edition text')),
                ('shelfmark', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('datepublication', models.CharField(blank=True, default='', max_length=255)),
                ('leaves', models.IntegerField(blank=True, null=True)),
                ('sourcecode', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.TextField(blank=True, default='')),
                ('publicationtitle', models.TextField(blank=True, default='')),
                ('imagesource', models.CharField(blank=True, default='', max_length=255)),
                ('platenumber', models.CharField(blank=True, default='', max_length=255)),
                ('additionalInformation', models.TextField(blank=True, default='')),
                ('keyFeatures', models.TextField(blank=True, default='')),
                ('volume', models.CharField(blank=True, default='', max_length=255)),
                ('accode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.accode')),
                ('archive', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.archive')),
                ('dedicatee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.dedicatee')),
                ('publisher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.publisher')),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.newsource')),
            ],
            options={
                'verbose_name': 'SourceInformation',
                'verbose_name_plural': 'SourceInformations',
            },
        ),
        migrations.CreateModel(
            name='NewPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surrogate', models.IntegerField(blank=True, null=True)),
                ('versionnumber', models.IntegerField(blank=True, null=True)),
                ('permission', models.BooleanField(default=False)),
                ('permissionnote', models.CharField(blank=True, default='', max_length=255)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('startbar', models.CharField(blank=True, default='', max_length=255)),
                ('endbar', models.CharField(blank=True, default='', max_length=255)),
                ('corrected', models.IntegerField(blank=True, default=0, null=True)),
                ('linked', models.IntegerField(blank=True, default=0, null=True)),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.newsource')),
            ],
            options={
                'verbose_name': 'NewPageImage',
                'verbose_name_plural': 'NewPageImages',
            },
        ),
        migrations.CreateModel(
            name='instrumentComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.instrument')),
                ('sourcecomponent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.sourcecomponent')),
            ],
            options={
                'verbose_name': 'instrumentComponent',
                'verbose_name_plural': 'instrumentComponents',
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='sourcecomponent',
            field=models.ManyToManyField(blank=True, through='ocve.SourceComponent_Instrument', to='ocve.SourceComponent'),
        ),
        migrations.AddField(
            model_name='genre_work',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.work'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='ocve.country'),
        ),
        migrations.CreateModel(
            name='BarSpine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, default='')),
                ('orderno', models.IntegerField(blank=True, default=0, null=True)),
                ('implied', models.IntegerField(blank=True, default=0, null=True)),
                ('bar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.bar')),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.source')),
                ('sourcecomponent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.sourcecomponent')),
            ],
        ),
        migrations.CreateModel(
            name='BarSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startbar', models.CharField(blank=True, default='', max_length=255)),
                ('endbar', models.CharField(blank=True, default='', max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='BarRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('anomaly', models.IntegerField(blank=True, default=0)),
                ('barid_old', models.IntegerField(blank=True, null=True)),
                ('annotation', models.ManyToManyField(blank=True, through='ocve.Annotation_BarRegion', to='ocve.Annotation')),
                ('bar', models.ManyToManyField(blank=True, through='ocve.Bar_BarRegion', to='ocve.Bar')),
                ('page', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barRegions', to='ocve.page')),
                ('pageimage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.pageimage')),
            ],
            options={
                'verbose_name': 'BarRegion',
                'verbose_name_plural': 'BarRegions',
            },
        ),
        migrations.CreateModel(
            name='BarCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('xystring', models.TextField(blank=True, default='')),
                ('regions', models.ManyToManyField(to='ocve.BarRegion')),
                ('user', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bar_barregion',
            name='barregion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.barregion'),
        ),
        migrations.AddField(
            model_name='archive',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.city'),
        ),
        migrations.AddField(
            model_name='annotation_barregion',
            name='barregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocve.barregion'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='pageimage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.pageimage'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocve.annotationtype'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
